### ISSUE TITLE
Configuração da aplicação

### ISSUE THREAD

**Issue by rafaelcanovas** [felbarboza/ACMEVita#1]
https://github.com/felbarboza/ACMEVita/blob/12d28db6a89b5e399d810b91e3bbe7f5c41ea69c/src/__init__.py#L10

Boa tarde Felipe, tudo bem?

A medida que uma aplicação vai crescendo, precisamos definir cada vez mais configurações e parâmetros. Como você faria neste caso para definir e carregar um grande número de configurações?

Abs!

**Comment by felbarboza** [comment]
Boa tarde Rafa, tudo bem e contigo?

Penso que a melhor maneira seria por um arquivo de configurações separado, config.py ou config.json por exemplo. E melhor ainda se o mesmo for modularizado, com objetos diferentes para cada configuração necessária.
Então importá-lo e carregar suas informações para a configuração do app.
E para configurações sensíveis que não podem estar no repositório penso que guardá-las no .env é a melhor opção.

Qualquer dúvida estou à disposição. 

Abs!

**Comment by rafaelcanovas** [comment]
Obrigado Felipe!
