### ISSUE TITLE
Alteração de modelos de dados

### ISSUE THREAD

**Issue by rafaelcanovas** [felbarboza/ACMEVita#2]
https://github.com/felbarboza/ACMEVita/blob/12d28db6a89b5e399d810b91e3bbe7f5c41ea69c/main.py#L6

Boa tarde Felipe, tudo bem?

Como sabemos o comando `create_all` cria todas as tabelas descritas pelos modelos de dados quando executado. É muito comum que ao longo da evolução de uma aplicação, esses modelos sejam alterados, novos campos sejam adicionados ou removidos. Neste caso como você procederia?

Abs.

**Comment by felbarboza** [comment]
Boa noite, Rafael, tudo bem?

Penso que a melhor maneira de controlar tais alterações é por meio de migrations. Pois todos que estão mexendo no código podem visualizar as mudanças de forma temporal.
Pode ser feito utilizando a biblioteca Flask-migrate que armazena tais mudanças em uma pasta e posteriormente é possível carregar as alterações no banco de dados.

Qualquer dúvida estou à disposição.

Abs.

**Comment by rafaelcanovas** [comment]
Obrigado Felipe!
