### ISSUE TITLE
Tipagem de dados

### ISSUE THREAD

**Issue by rafaelcanovas** [felbarboza/ACMEVita#3]
Boa tarde Felipe, tudo bem?

Qual é sua experiência com tipagem estática de dados no Python e como você acha que isso poderia contribuir para a sua aplicação?

Abs.

**Comment by felbarboza** [comment]
Boa noite, Rafael, tudo bem?

Já utilizei tipagem estática em poucos projetos na empresa, porém sou muito adepto à tipagem de modo geral. 
Penso que a tipagem na aplicação não só facilita a vida do desenvolvedor que, ao pegar um código entende melhor os tipos de cada variável e retorno de funções, como também previne bugs em decorrência disso.
E ao adaptar isso no time, por mais que no começo seja mais verboso, com o tempo, a adoção disso só tem a agregar.

Qualquer duvida estou a disposição.

Abs.

**Comment by rafaelcanovas** [comment]
Obrigado Felipe!
