### ISSUE TITLE
Validação de dados de entrada

### ISSUE THREAD

**Issue by rafaelcanovas** [felbarboza/ACMEVita#4]
https://github.com/felbarboza/ACMEVita/blob/12d28db6a89b5e399d810b91e3bbe7f5c41ea69c/src/colaborator/views/colaborator.py#L6-L14

Boa tarde Felipe, tudo bem?

Lendo o código da sua aplicação percebi que não há validação dos dados de entrada, ou seja, se o utilizador da API especificar um `department_id` do tipo string, sua aplicação vai tentar inserir no banco, causando um erro de integridade e consequentemente um erro 500. Como você faria para garantir a validação dos dados de entrada, trazendo mais qualidade e segurança para a sua API?

Abs.

**Comment by felbarboza** [comment]
Boa noite, Rafael, tudo bem?

Penso que existem diversas maneiras para resolver tal problema. Com verificação de tipos em python puro, por exemplo.
Porém existem bibliotecas mais aptas para tal função, como flask-marshmallow, que possibilita a verificação de tais parâmetros e facilita a codificação de mensagens de erros mais claras, além de facilitar a vida do desenvolvedor, com um código mais modular - com a criação de Schemas validadores - e menos passível de bugs.
No caso do código citado, eu faria um Schema CreateColaboratorInputSchema e verificaria se os tipos condizem, retornando mensagens de erro específicas para cada campo.

Qualquer duvida estou a disposição.

Abs.

**Comment by rafaelcanovas** [comment]
Obrigado Felipe!
